apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: my-k0s-cluster
spec:
  hosts:
  - role: controller+worker
    ssh:
      address: 100.115.118.34
      user: ubuntu
  - role: worker
    ssh:
      address: 100.91.101.107
      user: dixneuf19
  - role: worker
    ssh:
      address: 100.76.90.89
      user: dixneuf19
  - role: worker
    ssh:
      address: 100.100.239.37
      user: ubuntu
  k0s:
    version: v1.23.6+k0s.1
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: Cluster
      metadata:
        name: k0s
      spec:
        api:
          address: 100.115.118.34
          sans:
           - brassberry.dixneuf19.me
        telemetry:
          enabled: false
