apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: my-k0s-cluster
spec:
  hosts:
  - role: controller+worker
    ssh:
      address: 192.168.1.24
      user: ubuntu
  - role: worker
    ssh:
      address: 192.168.1.25
      user: ubuntu
  - role: worker
    ssh:
      address: 192.168.1.26
      user: ubuntu
  - role: worker
    ssh:
      address: 192.168.1.27
      user: ubuntu
  k0s:
    version: v1.21.8+k0s.0
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: Cluster
      metadata:
        name: k0s
      spec:
        api:
          address: 192.168.1.24
          sans:
           - brassberry.dixneuf19.me
        telemetry:
          enabled: false
