[all:vars]
ansible_ssh_user=ubuntu

# ## Configure 'ip' variable to bind kubernetes services on a
# ## different ip than the default iface
# ## We should set etcd_member_name for etcd cluster. The node that is not a etcd member do not need to set the value, or can set the empty string value.
[all]
brassberry-24 ansible_host=brassberry.dixneuf19.me ansible_port=1924
brassberry-25 ansible_host=brassberry.dixneuf19.me ansible_port=1925
brassberry-26 ansible_host=brassberry.dixneuf19.me ansible_port=1926

# ## configure a bastion host if your nodes are not directly reachable
# bastion ansible_host=x.x.x.x ansible_user=some_user

[kube-master]
brassberry-24

[kube-node]
brassberry-25
brassberry-26

[k8s-cluster:children]
kube-master
kube-node

