all:
  vars:
    ansible_ssh_user: ubuntu
    disks: []

master:
  hosts:
    brassberry-24:
      ansible_host: brassberry.dixneuf19.me
      ansible_port: 1924

workers:
  hosts:
    brassberry-25:
      ansible_host: brassberry.dixneuf19.me
      ansible_port: 1925
      disks:
      - name: tuyhoa_2T
        uuid: 2b0a49ce-d6c4-456d-a5a6-52850f9b0213
        type: EXT4
    brassberry-26:
      ansible_host: brassberry.dixneuf19.me
      ansible_port: 1926
      disks:
      - name: magadi_3T
        uuid: E6504EF8504ECECD
        type: NTFS
    brassberry-27:
      ansible_host: brassberry.dixneuf19.me
      ansible_port: 1927
      disks: []
