all:
  vars:
    ansible_ssh_user: ubuntu
    disks: []

master:
  hosts:
    brassberry-24:
      ansible_host: 100.115.118.34
workers:
  hosts:
    brassberry-25:
      ansible_ssh_user: dixneuf19
      ansible_host: 100.91.101.107
      disks:
      - name: tuyhoa_2T
        uuid: 2b0a49ce-d6c4-456d-a5a6-52850f9b0213
        type: EXT4
    brassberry-26:
      ansible_ssh_user: dixneuf19
      ansible_host:  100.76.90.89
    brassberry-27:
      ansible_host: 100.100.239.37
      disks:
      - name: magadi_3T
        uuid: E6504EF8504ECECD
        type: NTFS
