#################################################
# Setup Kubernetes
#################################################
---
- hosts: brassberry-26
  become: true

  tasks:
    - name: Update apt and install watchdog
      apt:
        name:
          - watchdog
        update_cache: yes
        state: latest

    - name: check if /etc/watchdog.conf backup exists
      stat: 
        path: /etc/watchdog.conf.backup
      register: watchdog_backup_exists

    - name: Make a backup copy of /etc/watchdog.conf file just in case
      copy:
        remote_src: true
        src: /etc/watchdog.conf
        dest: /etc/watchdog.conf.backup
      when: watchdog_backup_exists.stat.exists == False

    - name: override the basic watchdog configuration with our own file
      copy:
        src: ./files/watchdog.conf
        dest: /etc/watchdog.conf
        owner: root
        group: root
        mode: 0644


    - name: Reboot
      reboot: {}
